name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Set Creds
        run: git config user.name "zidaneiqbal" && git config user.email "raja.zidaneiqbal@gmail.com"

      - name: Deploy
        run: npm run deploy